services:
  rsync:
    build:
      context: .
      dockerfile: Dockerfile_rsync
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    command:
      - bash
      - -c
      - |
        set -ue
        if [ ! -d /src/cache/app ]; then mkdir -p /src/cache/app; fi
        if [ ! -d /src/cache/.gradle ]; then mkdir -p /src/cache/.gradle; fi
        rsync -avz --delete /src/ /src/cache/app \
          --exclude=.git \
          --exclude=.idea \
          --exclude=.claude \
          --exclude=.github \
          --exclude=.junie \
          --exclude=.kotlin \
          --exclude=.serena \
          --exclude=cache \
          --exclude=kotlin-js-store \
          --exclude=ktcl-front/node_modules \
          --exclude=kodel/api/build \
          --exclude=ktcp/model/build \
          --exclude=ktcp/server/build
    volumes:
      - type: bind
        source: .
        target: /src
  ktcl-front-test:
    image: node
    command:
      - bash
      - -c
      - |
        set -ue
        npm install
        npm run build
    working_dir: /app/ktcl-front
    depends_on:
      rsync:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: ./cache/app/ktcl-front
        target: /app/ktcl-front
      - type: bind
        source: ./cache/npm
        target: /root/.npm

  all-tests:
    build:
      context: .
      dockerfile: Dockerfile_testc
    command: ./gradlew allTests
    depends_on:
      rsync:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: ./cache/app
        target: /app
      - type: bind
        source: ./cache/.gradle
        target: /root/.gradle
    working_dir: /app
    environment:
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - CHROME_BIN=/opt/google/chrome/chrome
      - FIREFOX_BIN=/usr/bin/firefox
  test:
    build:
      context: .
      dockerfile: Dockerfile_test
    command: ./gradlew test
    depends_on:
      all-tests:
        condition: service_completed_successfully
      ktcl-front-test:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: ./cache/app
        target: /app
      - type: bind
        source: ./cache/.gradle
        target: /root/.gradle
    working_dir: /app
    environment:
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - CHROME_BIN=/opt/google/chrome/chrome
      - FIREFOX_BIN=/usr/bin/firefox

