FROM eclipse-temurin:25.0.1_8-jdk-noble

ENV JAVA_HOME=/opt/java/openjdk
ENV DEBIAN_FRONTEND=noninteractive
ENV ANDROID_HOME=/opt/android-sdk
ENV PATH="${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools"

RUN apt update && \
    apt install -y --no-install-recommends \
      wget gnupg ca-certificates apt-transport-https libatomic1 unzip && \
    install -d -m 0755 /etc/apt/keyrings && \
    wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O /etc/apt/keyrings/packages.mozilla.org.asc && \
    gpg -n -q --import --import-options import-show /etc/apt/keyrings/packages.mozilla.org.asc | \
      awk '/pub/{getline; gsub(/^ +| +$/,""); \
        if($0 == "35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3") \
          print "Mozilla key verified"; \
        else exit 1 }' && \
    printf "Types: deb\nURIs: https://packages.mozilla.org/apt\nSuites: mozilla\nComponents: main\nSigned-By: /etc/apt/keyrings/packages.mozilla.org.asc\n" \
      > /etc/apt/sources.list.d/mozilla.sources && \
    printf "Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000\n" \
      > /etc/apt/preferences.d/mozilla && \
    apt-get update && \
    apt-get install -y --no-install-recommends firefox && \
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y && \
    rm -f google-chrome-stable_current_amd64.deb && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p "${ANDROID_HOME}/cmdline-tools" && \
    wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdline-tools.zip && \
    unzip -q /tmp/cmdline-tools.zip -d /tmp/cmdline-tools-extract && \
    mv /tmp/cmdline-tools-extract/cmdline-tools "${ANDROID_HOME}/cmdline-tools/latest" && \
    rm -f /tmp/cmdline-tools.zip && \
    rm -rf /tmp/cmdline-tools-extract && \
    yes | sdkmanager --licenses > /dev/null && \
    sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

