FROM node:24-slim AS development-dependencies-env
COPY kicl-web /app
COPY kicl/kicl-domain/build/dist/js/productionLibrary /kicl/kicl-domain/build/dist/js/productionLibrary
COPY kicl/kicl-usecase/build/dist/js/productionLibrary /kicl/kicl-usecase/build/dist/js/productionLibrary
WORKDIR /app
RUN npm ci

FROM node:24-slim AS production-dependencies-env
COPY kicl-web/package.json kicl-web/package-lock.json /app/
COPY kicl/kicl-domain/build/dist/js/productionLibrary /kicl/kicl-domain/build/dist/js/productionLibrary
COPY kicl/kicl-usecase/build/dist/js/productionLibrary /kicl/kicl-usecase/build/dist/js/productionLibrary
WORKDIR /app
RUN npm ci --omit=dev

FROM node:24-slim AS build-env
COPY kicl-web /app
COPY kicl/kicl-domain/build/dist/js/productionLibrary /kicl/kicl-domain/build/dist/js/productionLibrary
COPY kicl/kicl-usecase/build/dist/js/productionLibrary /kicl/kicl-usecase/build/dist/js/productionLibrary
COPY --from=development-dependencies-env /app/node_modules /app/node_modules
WORKDIR /app
RUN npm run build

FROM node:24-slim
COPY kicl-web/package.json kicl-web/package-lock.json /app/
COPY kicl/kicl-domain/build/dist/js/productionLibrary /kicl/kicl-domain/build/dist/js/productionLibrary
COPY kicl/kicl-usecase/build/dist/js/productionLibrary /kicl/kicl-usecase/build/dist/js/productionLibrary
COPY --from=production-dependencies-env /app/node_modules /app/node_modules
COPY --from=build-env /app/build /app/build
WORKDIR /app
CMD ["npm", "run", "start"]
