FROM eclipse-temurin:25.0.1_8-jdk-noble AS builder

WORKDIR /app
COPY buildSrc /app/buildSrc
COPY gradle /app/gradle
COPY kodel /app/kodel
COPY ktcl-claudecode /app/ktcl-claudecode
COPY ktcp /app/ktcp
COPY ktse /app/ktse
COPY settings.gradle.kts gradle.properties build.gradle.kts gradlew /app/
RUN ./gradlew :ktse:build

FROM eclipse-temurin:25.0.1_8-jdk-noble

COPY --from=builder /app/ktse/build/libs/ktse-all.jar /app/app.jar
WORKDIR /work
ENTRYPOINT ["java"]
CMD ["-jar","/app/app.jar"]
