FROM node:20-alpine AS development-dependencies-env
COPY ktcl-front /app
WORKDIR /app
RUN npm ci

FROM node:20-alpine AS production-dependencies-env
COPY ktcl-front/package.json ktcl-front/package-lock.json /app/
WORKDIR /app
RUN npm ci --omit=dev

FROM node:20-alpine AS build-env
# ビルド時に必要な環境変数を定義
ARG VITE_WEBSOCKET_URL
ARG VITE_USER_ISSUER
ARG VITE_USER_CLIENT_ID
ARG VITE_KEYCLOAK_URL
ARG VITE_KEYCLOAK_REALM
ARG VITE_KEYCLOAK_CLIENT_ID

COPY ktcl-front /app/
COPY --from=development-dependencies-env /app/node_modules /app/node_modules
WORKDIR /app
RUN npm run build

FROM node:20-alpine
# 実行時に必要な環境変数を定義
ENV OWN_ISSUER=""
ENV PRIVATE_KEY=""
ENV KTSE_AUD="keruta"
ENV USER_JWKS_URL=""
ENV USER_ISSUER=""

COPY ktcl-front/package.json ktcl-front/package-lock.json /app/
COPY --from=production-dependencies-env /app/node_modules /app/node_modules
COPY --from=build-env /app/build /app/build
WORKDIR /app
CMD ["npm", "run", "start"]
