version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keruta-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=keruta
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=password
    restart: unless-stopped
    networks:
      - keruta-network

  mongodb:
    image: mongo:latest
    container_name: keruta-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=keruta
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - keruta-network

networks:
  keruta-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
