version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: keruta-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=keruta
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - keruta-network

networks:
  keruta-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
