/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // foojay-resolver - auto-provision toolchains
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "keruta"
fun Settings.includesIfExists(dir: String, vararg includes: String) {
    if (file(dir).exists()) this.include(*includes)
}

includesIfExists("kodel", "kodel:api", "kodel:coroutine", "kodel:core")
includesIfExists(
    "ktcp",
    "ktcp:ktcp-domain", "ktcp:ktcp-domain:ktcp-domain-server", "ktcp:ktcp-domain:ktcp-domain-client",
    "ktcp:ktcp-usecase", "ktcp:ktcp-usecase:ktcp-usecase-server", "ktcp:ktcp-usecase:ktcp-usecase-client",
    "ktcp:ktcp-infra", "ktcp:ktcp-infra:ktcp-infra-server","ktcp:ktcp-infra:ktcp-infra-client",
    "ktcp:client", "ktcp:server",
)
includesIfExists("ktse", "ktse")
includesIfExists("ktcl-claudecode", "ktcl-claudecode")
includesIfExists("ktcl-k8s", "ktcl-k8s")
includesIfExists("ktcl", "ktcl")
includesIfExists("ktcl-front-mobile", "ktcl-front-mobile", "ktcl-front-mobile:app")
