/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // foojay-resolver - auto-provision toolchains
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "keruta"
fun Settings.includesIfExists(dir: String, vararg includes: String) {
    if (file(dir).exists()) this.include(*includes)
}
@DslMarker
annotation class IncludeDslMarker

@IncludeDslMarker
class IncludeDsl(
    private val prefix: List<String>,
    private val settings: Settings,
) {
    fun includeIfExists(vararg name: String): Boolean = if (
        file(path(name).joinToString(separator = "/")).exists()
    ) {
        include(*name)
        true
    } else false


    fun include(vararg name: String) = settings.include(path(name).joinToString(separator = ":"))

    private fun path(name: Array<out String>) = (prefix + name).let { pathName ->
        var name: String? = null
        pathName.map {
            name = if (name == null) it
            else "$name-$it"
            name
        }
    }

    fun group(name: String, block: IncludeDsl.() -> Unit) = IncludeDsl(prefix + name, settings).block()
    fun includeIfExistsAndGroup(name: String, block: IncludeDsl.() -> Unit) =
        if (includeIfExists(name)) group(name, block)
        else Unit
}

fun Settings.includeDsl(block: IncludeDsl.() -> Unit) {
    IncludeDsl(emptyList(), this).block()
}
includesIfExists("kodel", "kodel:api", "kodel:coroutine", "kodel:core")
includesIfExists(
    "ktcp-sdk",
    "ktcp-sdk:ktcp-domain", "ktcp-sdk:ktcp-domain:ktcp-domain-server", "ktcp-sdk:ktcp-domain:ktcp-domain-client",
    "ktcp-sdk:ktcp-usecase", "ktcp-sdk:ktcp-usecase:ktcp-usecase-client",
    "ktcp-sdk:ktcp-infra-client",
    "ktcp-sdk:client",
)
includesIfExists("ktse-sdk", "ktse-sdk", "ktse-sdk:ktse-sdk-usecase")
includesIfExists("ktse", "ktse")
includesIfExists("ktcl-claudecode", "ktcl-claudecode")
includesIfExists("ktcl-k8s", "ktcl-k8s")
includesIfExists("ktcl-sdk", "ktcl-sdk")
includesIfExists("ktcl-front-mobile", "ktcl-front-mobile", "ktcl-front-mobile:app")

includeDsl {
    includeIfExistsAndGroup("kicp") {
        includeIfExists("domain")
        includeIfExists("usecase")
    }
}
