ktor:
  application:
    modules:
      - net.kigawa.keruta.ktcl.web.KerutaTaskClientWeb.module
  deployment:
    port: 8081
  security:
    keycloak:
      realm: develop
      issuer: https://user.kigawa.net/realms/develop
      audience: keruta-web
      jwkUrl: https://user.kigawa.net/realms/develop/protocol/openid-connect/certs
      clientId: ${OIDC_CLIENT_ID}
      clientSecret: ${OIDC_CLIENT_SECRET}
