ktor {
    deployment {
        port = 8081
        port = ${?KTCL_K8S_WEB_PORT}
    }
    application {
        modules = [ net.kigawa.keruta.ktcl.k8s.web.ApplicationKt.module ]
    }
}

keycloak {
    url = "https://user.kigawa.net/"
    url = ${?KEYCLOAK_URL}
    realm = "develop"
    realm = ${?KEYCLOAK_REALM}
    clientId = "keruta"
    clientId = ${?KEYCLOAK_CLIENT_ID}
    jwksUrl = ${keycloak.url}"realms/"${keycloak.realm}"/protocol/openid-connect/certs"
    issuer = ${keycloak.url}"realms/"${keycloak.realm}
}
