ktor:
  deployment:
    port: 8081
  application:
    modules:
      - net.kigawa.keruta.ktcl.k8s.KtclK8sServer.module

idp:
  issuer: ${IDP_ISSUER:https://user.kigawa.net/realms/develop}
  audience: ${IDP_AUDIENCE:keruta}
keruta:
  ownIssuer: ${KERUTA_ISSUER:http://localhost:8081}
