package net.kigawa.keruta.ktcp.model.err.server

enum class ServerErrCode {
    ENTRYPOINT_NOT_FOUND,
    ILLEGAL_FORMAT_DESERIALIZE,
    INVALID_TYPE_DESERIALIZE,
    INVALID_TYPE_DECODE_FRAME,
    DESERIALIZE_DECODE_FRAME,
    VERIFY_UNSUPPORTED_KEY,
    VERIFY_FAIL,
    UNEXPECTED
}
