package net.kigawa.keruta.ktcp.model.err.server

enum class ServerErrCode {
    INVALID_TYPE_DECODE_FRAME,
    DESERIALIZE_DECODE_FRAME,
    VERIFY_UNSUPPORTED_KEY,
    VERIFY_FAIL,
    UNEXPECTED,
    RESPONSE_ERR,
    UNAUTHENTICATED,
    BACKEND,
    UNKNOWN_ISSUER,
    MULTIPLE_RECORD,
    NO_SINGLE_RECORD
}
