ktor:
  application:
    modules:
      - net.kigawa.keruta.ktse.KerutaTaskServer.module
  deployment:
    port: 8080
  security:
    keycloak:
      realm: develop
      issuer: https://user.kigawa.net/realms/develop
      jwkUrl: https://user.kigawa.net/realms/develop/protocol/openid-connect/certs
      clientId: ${OIDC_CLIENT_ID}
      clientSecret: ${OIDC_CLIENT_SECRET}
