ktor:
  application:
    modules:
      - net.kigawa.keruta.ktse.KerutaTaskServer.module
  deployment:
    port: 8080
  security:
    defaultIdp:
      - issuer: https://user.kigawa.net/realms/develop
        audience: keruta
    defaultProvider:
      - issuer: http://127.0.0.1:5173/
        audience: keruta
        name: web
zk:
  host: ${ZK_HOST}
db:
  jdbcUrl: ${DB_JDBC_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
