ktor:
  application:
    modules:
      - net.kigawa.keruta.ktse.KerutaTaskServer.module
  deployment:
    port: 8080
  security:
    jwt:
      realm: develop
      issuer: https://user.kigawa.net/realms/develop
      audience: backend-b
      jwkUrl: https://user.kigawa.net/realms/develop/protocol/openid-connect/certs
