name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/ci.yml
      - buildSrc/**
      - gradle/**
      - kodel/**
      - ktcp/**
      - ktse/**
      - build.gradle.kts
      - gradle.properties
      - settings.gradle.kts
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/ci.yml
      - buildSrc/**
      - gradle/**
      - kodel/**
      - ktcp/**
      - ktse/**
      - build.gradle.kts
      - gradle.properties
      - settings.gradle.kts

jobs:
  ktcp:
    name: KTCP - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew :allTests --no-daemon

