name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ktcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          mkdir -p ./cache/app
          mkdir -p ./cache/.gradle
      - name: Cache something
        uses: actions/cache@v5
        with:
          path: ./cache
          key: ${{ runner.os }}-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-test-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: docker compose -f compose.test.yml up test --exit-code-from test --attach-dependencies
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
      - run: docker compose -f compose.test.yml logs test
        if: always()
      - run: docker compose -f compose.test.yml logs ktcl-front-test
        if: always()
      - run: docker compose -f compose.test.yml logs all-tests
        if: always()
