name: dev-ktcl-front
on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile_ktse
      - Dockerfile_ktcl_k8s
      - Dockerfile_ktcl_claudecode
      - ktcl-k8s/**
      - .github/workflows/dev-ktcl-k8s.yml
      - .github/workflows/dev-ktse.yml
      - .github/workflows/renovate.yaml
      - .github/renovate.json
      - .idea/**
      - ktcl-k8s/**
      - ktcl-claudecode/**
      - ktcl-front-mobile/**
      - ktcp/server/**
      - ktse/**
    branches:
      - develop

jobs:
  ktcl-front:
    uses: ./.github/workflows/release.yml
    secrets:
      HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      name: ktcl-front
      manifestFile: ./keruta/dev/ktcl-front.yaml
      harborProject: "private"
      repository: "kigawa-net/kigawa-net-k8s"
      dockerFile: './Dockerfile_ktcl_front'
      buildArgs: |
        {
          "VITE_WEBSOCKET_URL": "wss://ktse-dev.kigawa.net/ws/ktcp",
          "VITE_USER_ISSUER": "https://user.kigawa.net/realms/develop",
          "VITE_USER_CLIENT_ID": "keruta",
          "VITE_KEYCLOAK_URL": "https://user.kigawa.net/",
          "VITE_KEYCLOAK_REALM": "develop",
          "VITE_KEYCLOAK_CLIENT_ID": "keruta"
        }

