name: Generate OpenAPI Specification

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'infra/**'
      - '.github/workflows/generate-openapi.yml'

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build and run application
        run: |
          ./gradlew bootRun --args='--spring.profiles.active=test' &
          echo "Waiting for application to start..."
          sleep 120  # Give the application time to start

      - name: Generate OpenAPI specification
        run: |
          mkdir -p keruta-doc/common/apiSpec
          curl -s http://localhost:8080/api-docs > keruta-doc/common/apiSpec/openapi.json
          curl -s http://localhost:8080/api-docs.yaml > keruta-doc/common/apiSpec/openapi.yaml
          echo "OpenAPI specification generated"

      - name: Clone keruta-doc repository
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/kigawa-net/keruta-doc.git /tmp/keruta-doc
          mkdir -p /tmp/keruta-doc/common/apiSpec
          cp keruta-doc/common/apiSpec/openapi.json /tmp/keruta-doc/common/apiSpec/
          cp keruta-doc/common/apiSpec/openapi.yaml /tmp/keruta-doc/common/apiSpec/
          cp keruta-doc/README.md /tmp/keruta-doc/
          cp keruta-doc/structure.md /tmp/keruta-doc/
          cp keruta-doc/todo.md /tmp/keruta-doc/

      - name: Commit and push to keruta-doc repository
        run: |
          cd /tmp/keruta-doc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add common/apiSpec/openapi.json common/apiSpec/openapi.yaml
          git add README.md structure.md todo.md
          git commit -m "Update documentation and OpenAPI specification" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
