name: Generate OpenAPI Specification

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'infra/**'
      - '.github/workflows/generate-openapi.yml'

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build and run application
        run: |
          ./gradlew bootRun --args='--spring.profiles.active=test' &
          echo "Waiting for application to start..."
          sleep 60  # Give the application time to start

      - name: Generate OpenAPI specification
        run: |
          mkdir -p keruta-doc/common/apiSpec
          curl -s http://localhost:8080/api-docs > keruta-doc/common/apiSpec/openapi.json
          curl -s http://localhost:8080/api-docs.yaml > keruta-doc/common/apiSpec/openapi.yaml
          echo "OpenAPI specification generated"

      - name: Commit and push OpenAPI specification
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add keruta-doc/common/apiSpec/openapi.json keruta-doc/common/apiSpec/openapi.yaml
          git commit -m "Update OpenAPI specification" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
