name: ktcl-k8s-dev
on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile_ktse
      - Dockerfile_ktcl_front
      - Dockerfile_ktcl_claudecode
      - .github/workflows/dev-ktcl-front.yml
      - .github/workflows/dev-ktse.yml
      - .github/workflows/renovate.yaml
      - .github/renovate.json
      - .idea/**
      - ktcl-claudecode/**
      - ktcl-front/**
      - ktcl-front-mobile/**
      - ktcp/server/**
      - ktse/**
    branches:
      - develop

jobs:

  ktcl-k8s:
    uses: ./.github/workflows/release.yml
    secrets:
      HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      name: ktcl-k8s
      manifestFile: ./keruta/dev/ktcl-k8s.yaml
      harborProject: "library"
      repository: "kigawa-net/kigawa-net-k8s"
      dockerFile: './Dockerfile_ktcl_k8s'
      gradleTask: ':ktcl-k8s:shadowJar -x test'
      yamlPath: '.[0].spec.template.spec.containers[0].image'
