name: ktse-main
on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile_ktcl_k8s
      - Dockerfile_ktcl_front
      - Dockerfile_ktcl_claudecode
      - ktcl-k8s/**
      - .github/workflows/dev-ktcl-front.yml
      - .github/workflows/dev-ktcl-k8s.yml
      - .github/workflows/renovate.yaml
      - .github/renovate.json
      - .idea/**
      - ktcl-k8s/**
      - ktcl-front/**
      - ktcl-front-mobile/**
      - ktcl-claudecode/**
      - ktcp/client/**
      - ktcl/**
    branches:
      - main

jobs:
  ktse:
    uses: ./.github/workflows/release.yml
    secrets:
      HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      name: ktse
      manifestFile: ./keruta/main/ktse.yaml
      harborProject: "library"
      repository: "kigawa-net/kigawa-net-k8s"
      dockerFile: './Dockerfile_ktse'
      gradleTask: ':ktse:shadowJar -x test'
      yamlPath: 'select(documentIndex == 0).spec.template.spec.containers[0].image'
